<a href="https://colab.research.google.com/github/AntoninaStadnik/ITStep-AI/blob/superwised_learning/%D0%94%D0%97_pandas_hm_16.09.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Імпортуйте модуль pandas

In [1]:
import numpy as np
import pandas as pd

# Інформація про дані
Зібрано дані продажу техніки в різних магазинах.
* OrderDate -- дата замовлення
* Region    -- регіон де розміщено магазин
* Manager   -- ім'я менеджера
* SalesMan  -- ім'я продавця
* Item      -- тип товару
* Units     -- кількість купленого товару
* Unit_price -- ціна за штуку
* Sale_amt   -- загальна вартість покупки

In [5]:
df = pd.read_csv("https://raw.githubusercontent.com/HalyshAnton/IT-Step-Pyton-AI/main/module2/data/sales_data.csv", index_col="Unnamed: 0")

# Завдання 1

Вивести загальну інформацію про таблицю: кількість рядків та стовпців, назви стовпців та їхній тип даних, в яких стовпцях є пропущені значення

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 45 entries, 0 to 44
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   OrderDate   43 non-null     object
 1   Region      43 non-null     object
 2   Manager     43 non-null     object
 3   SalesMan    43 non-null     object
 4   Item        43 non-null     object
 5   Units       45 non-null     float64
 6   Unit_price  45 non-null     float64
 7   Sale_amt    45 non-null     float64
dtypes: float64(3), object(5)
memory usage: 3.2+ KB

In [4]:
df.shape

(45, 8)

In [9]:
df.head()

,orderdate,region,manager,salesman,item,units,unit_price,sale_amt
0,2018-01-06,East,Martha,Alexander,Television,95.0,1198.0,113810.0
1,2018-01-23,Central,Hermann,Shelli,Home Theater,50.0,500.0,25000.0
2,2018-02-09,Central,Hermann,Luis,Television,36.0,1198.0,43128.0
3,2018-02-26,Central,Timothy,David,Cell Phone,27.0,225.0,6075.0
4,2018-03-15,West,Timothy,Stephen,Television,56.0,1198.0,67088.0

# Завдання 2

Перейменуйте стовпчики так, щоб назви містили літери нижнього регістру

In [10]:
df.columns = df.columns.str.lower()
df.head()

,orderdate,region,manager,salesman,item,units,unit_price,sale_amt
0,2018-01-06,East,Martha,Alexander,Television,95.0,1198.0,113810.0
1,2018-01-23,Central,Hermann,Shelli,Home Theater,50.0,500.0,25000.0
2,2018-02-09,Central,Hermann,Luis,Television,36.0,1198.0,43128.0
3,2018-02-26,Central,Timothy,David,Cell Phone,27.0,225.0,6075.0
4,2018-03-15,West,Timothy,Stephen,Television,56.0,1198.0,67088.0

# Завдання 3
Виведіть дані про купівлі телевізорів та телефонів

In [12]:
mask_television = df['item'] == 'Television'

mask_television

0      True
1     False
2      True
3     False
4      True
5     False
6      True
7      True
8      True
9     False
10     True
11    False
12    False
13     True
14    False
15    False
16    False
17    False
18    False
19    False
20     True
21    False
22    False
23    False
24    False
25    False
26    False
27     True
28    False
29     True
30    False
31    False
32    False
33    False
34    False
35    False
36     True
37    False
38    False
39     True
40    False
41    False
42    False
43    False
44    False
Name: item, dtype: bool

In [13]:
mask_phone = df['item'] == 'Cell Phone'

mask_phone

0     False
1     False
2     False
3      True
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17     True
18     True
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28     True
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37     True
38    False
39    False
40    False
41    False
42    False
43    False
44    False
Name: item, dtype: bool

In [16]:
new_df1 = df[df['item'].isin(['Television', 'Cell Phone'])]
new_df1

,orderdate,region,manager,salesman,item,units,unit_price,sale_amt
0,2018-01-06,East,Martha,Alexander,Television,95.0,1198.0,113810.0
2,2018-02-09,Central,Hermann,Luis,Television,36.0,1198.0,43128.0
3,2018-02-26,Central,Timothy,David,Cell Phone,27.0,225.0,6075.0
4,2018-03-15,West,Timothy,Stephen,Television,56.0,1198.0,67088.0
6,2018-04-18,Central,Martha,Steven,Television,75.0,1198.0,89850.0
7,2018-05-05,Central,Hermann,Luis,Television,90.0,1198.0,107820.0
8,2018-05-22,West,Douglas,Michael,Television,32.0,1198.0,38336.0
10,2018-06-25,Central,Hermann,Sigal,Television,90.0,1198.0,107820.0
13,2018-08-15,East,Martha,Alexander,Television,35.0,1198.0,41930.0
17,2018-10-22,East,Martha,Alexander,Cell Phone,64.0,225.0,14400.0
18,2018-11-08,East,Douglas,Karen,Cell Phone,15.0,225.0,3375.0
20,2018-12-12,Central,Douglas,John,Television,67.0,1198.0,80266.0
27,2019-04-10,Central,Martha,Steven,Television,66.0,1198.0,79068.0
28,2019-04-27,East,Martha,Diana,Cell Phone,96.0,225.0,21600.0
29,2019-05-14,Central,Timothy,David,Television,53.0,1198.0,63494.0
36,2019-09-10,Central,Timothy,David,Television,7.0,1198.0,8386.0
37,2019-09-27,West,Timothy,Stephen,Cell Phone,76.0,225.0,17100.0
39,2019-10-31,Central,Martha,Steven,Television,14.0,1198.0,16772.0

# Завдання 4
Яка загальна виручка у продавця Luis?

In [17]:
luis_revenue = df[df['salesman'] == 'Luis']['sale_amt'].sum()

luis_revenue

np.float64(206373.0)

# Завдання 5

Скільки і якого товару було продано?

див groupby(),

In [18]:
new_df = df.groupby('item').size().reset_index(name='units')

new_df

           item  units
0    Cell Phone      5
1          Desk      3
2  Home Theater     15
3    Television     13
4   Video Games      7

# Завдання 6
Перевірте чи правильно розраховано загальну вартість покупки. Виведіть ті рядки де є помилка. Виправте дані в таблиці

In [21]:
mask_error = df['sale_amt'] != df['units'] * df['unit_price']

df[mask_error]

Empty DataFrame
Columns: [orderdate, region, manager, salesman, item, units, unit_price, sale_amt]
Index: []

In [20]:
df.loc[mask_error, 'sale_amt'] = df.loc[mask_error, 'units'] * df.loc[mask_error, 'unit_price']

In [22]:
df[df['sale_amt'] != df['units'] * df['unit_price']]

Empty DataFrame
Columns: [orderdate, region, manager, salesman, item, units, unit_price, sale_amt]
Index: []